import cv2
import numpy as np
img1 = cv2.imread('test.jpg')
img2 = cv2.imread('pika.png')
# res = cv2.bitwise_not(img1, img2)
# white = np.zeros((img1.shape[0], img1.shape[1], 3), dtype=np.uint8)
# white.fill(255)
# res = cv2.absdiff(img1,white)
# gray = cv2.cvtColor(img1, cv2.COLOR_BGR2GRAY)
# gray = [int(0.299 * p[0] + 0.587 * p[1] + 0.114 * p[2]) for p in img1[0]]
# gray = np.array(gray)
# res = cv2.inRange(gray,100,200)
# res = cv2.flip(img1, -1)
# res = cv2.mean(img1)
# b,g,r = cv2.split(img1)
# splitted = cv2.split(gray)
# print(len(splitted)
gray1 = cv2.cvtColor(img1, cv2.COLOR_BGR2GRAY)
img2 = cv2.resize(img2, (img1.shape[1], img1.shape[0]))
gray2 = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)
res = cv2.sum(gray2, gray1)
# zeros = np.zeros((img1.shape[0], img1.shape[1]), img1.dtype)
# res = cv2.merge((b,zeros,zeros))
cv2.imwrite('result.png', res)
